# Generated by Django 3.0.7 on 2020-08-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('includedtoppings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('availablesizes', models.ManyToManyField(blank=True, related_name='oftypes', to='orders.Size')),
                ('availablevariants', models.ManyToManyField(blank=True, related_name='oftypes', to='orders.Variant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizeprices', to='orders.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.Size')),
            ],
            options={
                'unique_together': {('product', 'price', 'size')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.ProductType'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.Variant'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datemodified', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='orders', to='orders.Item')),
                ('status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='productsizeprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ProductSizePrice'),
        ),
        migrations.AddField(
            model_name='item',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='items', to='orders.Topping'),
        ),
        migrations.CreateModel(
            name='ToppingAddPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabletoppings', to='orders.Product')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppingprices', to='orders.Topping')),
            ],
            options={
                'unique_together': {('topping', 'product')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('type', 'variant')},
        ),
    ]
