# Generated by Django 3.0.7 on 2020-08-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
    ]
