# Generated by Django 3.0.7 on 2020-07-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ticketspermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketsPermission',
        ),
    ]
