# Generated by Django 3.0.7 on 2020-07-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('base', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.PizzaBase')),
            ],
            bases=('orders.product',),
        ),
    ]
