# Generated by Django 3.0.7 on 2020-07-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pizza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
