# Generated by Django 3.0.7 on 2020-07-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_ticketspermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PizzaBase',
        ),
    ]
