# Generated by Django 3.0.7 on 2020-07-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='includedtoppings',
            field=models.IntegerField(default=0),
        ),
    ]
